name: app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  just_audio: ^0.10.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/jsons/
    - assets/audio/qaida/lesson1/
    - assets/audio/qaida/lesson2/
    - assets/audio/qaida/lesson3/
    - assets/audio/qaida/lesson4/
    - assets/audio/qaida/lesson5/
    - assets/audio/qaida/lesson11/
    - assets/audio/qaida/lesson12/

  fonts:
    - family: Uthmani
      fonts:
        - asset: assets/fonts/Uthmani.ttf
