import 'package:app/core/models/harakat_model.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

class HarakatsNotifier extends StateNotifier<List<HarakatModel>> {
  HarakatsNotifier()
    : super([
        HarakatModel(
          harfId: 1,
          fatha: 'اَ',
          fathaAuidoPath: '',
          dammah: 'اُ',
          dammahAuidoPath: '',
          kasrah: 'اِ',
          kasrahAuidoPath: '',
        ),
        HarakatModel(
          harfId: 2,
          fatha: 'بَ',
          fathaAuidoPath: '',
          dammah: 'بُ',
          dammahAuidoPath: '',
          kasrah: 'بِ',
          kasrahAuidoPath: '',
        ),
        HarakatModel(
          harfId: 3,
          fatha: 'تَ',
          fathaAuidoPath: '',
          dammah: 'تُ',
          dammahAuidoPath: '',
          kasrah: 'تِ',
          kasrahAuidoPath: '',
        ),
        HarakatModel(
          harfId: 4,
          fatha: 'ثَ',
          fathaAuidoPath: '',
          dammah: 'ثُ',
          dammahAuidoPath: '',
          kasrah: 'ثِ',
          kasrahAuidoPath: '',
        ),
        HarakatModel(
          harfId: 5,
          fatha: 'جَ',
          fathaAuidoPath: '',
          dammah: 'جُ',
          dammahAuidoPath: '',
          kasrah: 'جِ',
          kasrahAuidoPath: '',
        ),
        HarakatModel(
          harfId: 6,
          fatha: 'حَ',
          fathaAuidoPath: '',
          dammah: 'حُ',
          dammahAuidoPath: '',
          kasrah: 'حِ',
          kasrahAuidoPath: '',
        ),
        HarakatModel(
          harfId: 7,
          fatha: 'خَ',
          fathaAuidoPath: '',
          dammah: 'خُ',
          dammahAuidoPath: '',
          kasrah: 'خِ',
          kasrahAuidoPath: '',
        ),
        HarakatModel(
          harfId: 8,
          fatha: 'دَ',
          fathaAuidoPath: '',
          dammah: 'دُ',
          dammahAuidoPath: '',
          kasrah: 'دِ',
          kasrahAuidoPath: '',
        ),
        HarakatModel(
          harfId: 9,
          fatha: 'ذَ',
          fathaAuidoPath: '',
          dammah: 'ذُ',
          dammahAuidoPath: '',
          kasrah: 'ذِ',
          kasrahAuidoPath: '',
        ),
        HarakatModel(
          harfId: 10,
          fatha: 'رَ',
          fathaAuidoPath: '',
          dammah: 'رُ',
          dammahAuidoPath: '',
          kasrah: 'رِ',
          kasrahAuidoPath: '',
        ),
        HarakatModel(
          harfId: 11,
          fatha: 'زَ',
          fathaAuidoPath: '',
          dammah: 'زُ',
          dammahAuidoPath: '',
          kasrah: 'زِ',
          kasrahAuidoPath: '',
        ),
        HarakatModel(
          harfId: 12,
          fatha: 'سَ',
          fathaAuidoPath: '',
          dammah: 'سُ',
          dammahAuidoPath: '',
          kasrah: 'سِ',
          kasrahAuidoPath: '',
        ),
        HarakatModel(
          harfId: 13,
          fatha: 'شَ',
          fathaAuidoPath: '',
          dammah: 'شُ',
          dammahAuidoPath: '',
          kasrah: 'شِ',
          kasrahAuidoPath: '',
        ),
        HarakatModel(
          harfId: 14,
          fatha: 'صَ',
          fathaAuidoPath: '',
          dammah: 'صُ',
          dammahAuidoPath: '',
          kasrah: 'صِ',
          kasrahAuidoPath: '',
        ),
        HarakatModel(
          harfId: 15,
          fatha: 'ضَ',
          fathaAuidoPath: '',
          dammah: 'ضُ',
          dammahAuidoPath: '',
          kasrah: 'ضِ',
          kasrahAuidoPath: '',
        ),
        HarakatModel(
          harfId: 16,
          fatha: 'طَ',
          fathaAuidoPath: '',
          dammah: 'طُ',
          dammahAuidoPath: '',
          kasrah: 'طِ',
          kasrahAuidoPath: '',
        ),
        HarakatModel(
          harfId: 17,
          fatha: 'ظَ',
          fathaAuidoPath: '',
          dammah: 'ظُ',
          dammahAuidoPath: '',
          kasrah: 'ظِ',
          kasrahAuidoPath: '',
        ),
        HarakatModel(
          harfId: 18,
          fatha: 'عَ',
          fathaAuidoPath: '',
          dammah: 'عُ',
          dammahAuidoPath: '',
          kasrah: 'عِ',
          kasrahAuidoPath: '',
        ),
        HarakatModel(
          harfId: 19,
          fatha: 'غَ',
          fathaAuidoPath: '',
          dammah: 'غُ',
          dammahAuidoPath: '',
          kasrah: 'غِ',
          kasrahAuidoPath: '',
        ),
        HarakatModel(
          harfId: 20,
          fatha: 'فَ',
          fathaAuidoPath: '',
          dammah: 'فُ',
          dammahAuidoPath: '',
          kasrah: 'فِ',
          kasrahAuidoPath: '',
        ),
        HarakatModel(
          harfId: 21,
          fatha: 'قَ',
          fathaAuidoPath: '',
          dammah: 'قُ',
          dammahAuidoPath: '',
          kasrah: 'قِ',
          kasrahAuidoPath: '',
        ),
        HarakatModel(
          harfId: 22,
          fatha: 'كَ',
          fathaAuidoPath: '',
          dammah: 'كُ',
          dammahAuidoPath: '',
          kasrah: 'كِ',
          kasrahAuidoPath: '',
        ),
        HarakatModel(
          harfId: 23,
          fatha: 'لَ',
          fathaAuidoPath: '',
          dammah: 'لُ',
          dammahAuidoPath: '',
          kasrah: 'لِ',
          kasrahAuidoPath: '',
        ),
        HarakatModel(
          harfId: 24,
          fatha: 'مَ',
          fathaAuidoPath: '',
          dammah: 'مُ',
          dammahAuidoPath: '',
          kasrah: 'مِ',
          kasrahAuidoPath: '',
        ),
        HarakatModel(
          harfId: 25,
          fatha: 'نَ',
          fathaAuidoPath: '',
          dammah: 'نُ',
          dammahAuidoPath: '',
          kasrah: 'نِ',
          kasrahAuidoPath: '',
        ),
        HarakatModel(
          harfId: 26,
          fatha: 'هَ',
          fathaAuidoPath: '',
          dammah: 'هُ',
          dammahAuidoPath: '',
          kasrah: 'هِ',
          kasrahAuidoPath: '',
        ),
        HarakatModel(
          harfId: 27,
          fatha: 'وَ',
          fathaAuidoPath: '',
          dammah: 'وُ',
          dammahAuidoPath: '',
          kasrah: 'وِ',
          kasrahAuidoPath: '',
        ),
        HarakatModel(
          harfId: 28,
          fatha: 'ءَ',
          fathaAuidoPath: '',
          dammah: 'ءُ',
          dammahAuidoPath: '',
          kasrah: 'ءِ',
          kasrahAuidoPath: '',
        ),
        HarakatModel(
          harfId: 29,
          fatha: 'يَ',
          fathaAuidoPath: '',
          dammah: 'يُ',
          dammahAuidoPath: '',
          kasrah: 'يِ',
          kasrahAuidoPath: '',
        ),
      ]);
}

// -----------------------------------------------------------------------------
final harakatsProvider =
    StateNotifierProvider<HarakatsNotifier, List<HarakatModel>>((ref) {
      return HarakatsNotifier();
    });
