import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../../core/models/harf_model.dart';

class HurufNotifier extends StateNotifier<List<Harf>> {
  HurufNotifier()
    : super([
        Harf(
          id: 1,
          isolated: 'ا',
          start: 'أ',
          mid: 'ـأ',
          end: 'ـأ',
          arPronunciation: 'اَﻟِﻒْ',
          enPronunciation: 'Alif',
        ),
        Harf(
          id: 2,
          isolated: 'ب',
          start: 'بـ',
          mid: 'ـبـ',
          end: 'ـب',
          arPronunciation: 'ﺑَﺎ',
          enPronunciation: 'Ba',
        ),
        Harf(
          id: 3,
          isolated: 'ت',
          start: 'تـ',
          mid: 'ـتـ',
          end: 'ـت',
          arPronunciation: 'ﺗَﺎ',
          enPronunciation: 'Ta',
        ),
        Harf(
          id: 4,
          isolated: 'ث',
          start: 'ثـ',
          mid: 'ـثـ',
          end: 'ـث',
          arPronunciation: 'ﺛَﺎ',
          enPronunciation: 'T-Saa',
        ),
        Harf(
          id: 5,
          isolated: 'ج',
          start: 'جـ',
          mid: 'ـجـ',
          end: 'ـج',
          arPronunciation: 'ﺟِﻴﻢ',
          enPronunciation: 'Jeem',
        ),
        Harf(
          id: 6,
          isolated: 'ح',
          start: 'حـ',
          mid: 'ـحـ',
          end: 'ـح',
          arPronunciation: 'ﺣَﺎ',
          enPronunciation: 'Haa’',
        ),
        Harf(
          id: 7,
          isolated: 'خ',
          start: 'خـ',
          mid: 'ـخـ',
          end: 'ـخ',
          arPronunciation: 'ﺧَﺎ',
          enPronunciation: 'Kh-wo',
        ),
        Harf(
          id: 8,
          isolated: 'د',
          start: 'ـد',
          mid: 'ـد',
          end: 'ـد',
          arPronunciation: 'دَالْ',
          enPronunciation: 'Daal',
        ),
        Harf(
          id: 9,
          isolated: 'ذ',
          start: 'ـذ',
          mid: 'ـذ',
          end: 'ـذ',
          arPronunciation: 'ذَالْ',
          enPronunciation: 'Zaal',
        ),
        Harf(
          id: 10,
          isolated: 'ر',
          start: 'ـر',
          mid: 'ـر',
          end: 'ـر',
          arPronunciation: 'رَا',
          enPronunciation: 'Ra-wo',
        ),
        Harf(
          id: 11,
          isolated: 'ز',
          start: 'ـز',
          mid: 'ـز',
          end: 'ـز',
          arPronunciation: 'زَا',
          enPronunciation: 'Zaa',
        ),
        Harf(
          id: 12,
          isolated: 'س',
          start: 'سـ',
          mid: 'ـسـ',
          end: 'ـس',
          arPronunciation: 'ﺳِﻴْﻦْ',
          enPronunciation: 'Seen',
        ),
        Harf(
          id: 13,
          isolated: 'ش',
          start: 'شـ',
          mid: 'ـشـ',
          end: 'ـش',
          arPronunciation: 'ﺷِﻴْﻦْ',
          enPronunciation: 'Sheen',
        ),
        Harf(
          id: 14,
          isolated: 'ص',
          start: 'صـ',
          mid: 'ـصـ',
          end: 'ـص',
          arPronunciation: 'ﺻَﺎدْ',
          enPronunciation: 'Swaad',
        ),
        Harf(
          id: 15,
          isolated: 'ض',
          start: 'ضـ',
          mid: 'ـضـ',
          end: 'ـض',
          arPronunciation: 'ﺿَﺎد',
          enPronunciation: 'Dwaad',
        ),
        Harf(
          id: 16,
          isolated: 'ط',
          start: 'طـ',
          mid: 'ـطـ',
          end: 'ـط',
          arPronunciation: 'طَا',
          enPronunciation: 'Twaa',
        ),
        Harf(
          id: 17,
          isolated: 'ظ',
          start: 'ظـ',
          mid: 'ـظـ',
          end: 'ـظ',
          arPronunciation: 'ﻇَﺎ',
          enPronunciation: 'Zwaa',
        ),
        Harf(
          id: 18,
          isolated: 'ع',
          start: 'عـ',
          mid: 'ـعـ',
          end: 'ـع',
          arPronunciation: 'ﻋَﻴْﻦْ',
          enPronunciation: 'Aa’yn',
        ),
        Harf(
          id: 19,
          isolated: 'غ',
          start: 'غـ',
          mid: 'ـغـ',
          end: 'ـغ',
          arPronunciation: 'ﻏَﻴْﻦْ',
          enPronunciation: 'Gwoin',
        ),
        Harf(
          id: 20,
          isolated: 'ف',
          start: 'فـ',
          mid: 'ـفـ',
          end: 'ـف',
          arPronunciation: 'ﻓَﺎ',
          enPronunciation: 'Fa',
        ),
        Harf(
          id: 21,
          isolated: 'ق',
          start: 'قـ',
          mid: 'ـقـ',
          end: 'ـق',
          arPronunciation: 'ﻗَﺎفْ',
          enPronunciation: 'Qwof',
        ),
        Harf(
          id: 22,
          isolated: 'ك',
          start: 'كـ',
          mid: 'ـكـ',
          end: 'ـك',
          arPronunciation: 'ﻛﺎَفْ',
          enPronunciation: 'Kaaf',
        ),
        Harf(
          id: 23,
          isolated: 'ل',
          start: 'لـ',
          mid: 'ـلـ',
          end: 'ـل',
          arPronunciation: 'ﻻَمْ',
          enPronunciation: 'Laam',
        ),
        Harf(
          id: 24,
          isolated: 'م',
          start: 'مـ',
          mid: 'ـمـ',
          end: 'ـم',
          arPronunciation: 'ﻣِﻴْﻢْ',
          enPronunciation: 'Meem',
        ),
        Harf(
          id: 25,
          isolated: 'ن',
          start: 'نـ',
          mid: 'ـنـ',
          end: 'ـن',
          arPronunciation: 'ﻧُﻮْنْ',
          enPronunciation: 'Noon',
        ),
        Harf(
          id: 26,
          isolated: 'ه',
          start: 'هـ',
          mid: 'ـهـ',
          end: 'ـه',
          arPronunciation: 'ﻫَا',
          enPronunciation: 'Haa',
        ),
        Harf(
          id: 27,
          isolated: 'و',
          start: 'ـو',
          mid: 'ـو',
          end: 'ـو',
          arPronunciation: 'وَاوْ',
          enPronunciation: 'Waw',
        ),
        Harf(
          id: 28,
          isolated: 'ء',
          start: 'ء',
          mid: 'ء',
          end: 'ء',
          arPronunciation: 'هَمْزَ',
          enPronunciation: 'Hamza',
        ),
        Harf(
          id: 29,
          isolated: 'ي',
          start: 'يـ',
          mid: 'ـيـ',
          end: 'ـي',
          arPronunciation: 'ﻳَﺎ',
          enPronunciation: 'Ya',
        ),
      ]);
}

// -----------------------------------------------------------------------------
final hurufProvider = StateNotifierProvider<HurufNotifier, List<Harf>>((ref) {
  return HurufNotifier();
});
